alias gs='git status'
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git log'
alias glo='git log --oneline'
alias ga='git add'
alias gA='git add -A'
alias gr='git restore'
alias grs='git restore --staged'
alias grws='git restore --staged --worktree'
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gp='git push'
alias gb='git branch'

alias be='bundle exec'
alias ber='bundle exec rails'
